package com.study.repository.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class Log implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_name
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.time
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private Long time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.ip
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.create_time
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.location
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_name
     *
     * @return the value of log.user_name
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_name
     *
     * @param userName the value for log.user_name
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.time
     *
     * @return the value of log.time
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.time
     *
     * @param time the value for log.time
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.ip
     *
     * @return the value of log.ip
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.ip
     *
     * @param ip the value for log.ip
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.create_time
     *
     * @return the value of log.create_time
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.create_time
     *
     * @param createTime the value for log.create_time
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.location
     *
     * @return the value of log.location
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.location
     *
     * @param location the value for log.location
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", time=").append(time);
        sb.append(", ip=").append(ip);
        sb.append(", createTime=").append(createTime);
        sb.append(", location=").append(location);
        sb.append("]");
        return sb.toString();
    }
}