package com.study.repository.entity.generate;

import java.io.Serializable;

public class LogWithBLOBs extends Log implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operation
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.method
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.params
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operation
     *
     * @return the value of log.operation
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operation
     *
     * @param operation the value for log.operation
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.method
     *
     * @return the value of log.method
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.method
     *
     * @param method the value for log.method
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.params
     *
     * @return the value of log.params
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.params
     *
     * @param params the value for log.params
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    public void setParams(String params) {
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", operation=").append(operation);
        sb.append(", method=").append(method);
        sb.append(", params=").append(params);
        sb.append("]");
        return sb.toString();
    }
}