package com.study.repository.dao.generate;

import com.study.repository.entity.generate.Log;
import com.study.repository.entity.generate.LogExample;
import com.study.repository.entity.generate.LogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int insert(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int insertSelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    List<LogWithBLOBs> selectByExampleWithBLOBsWithRowbounds(LogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    List<LogWithBLOBs> selectByExampleWithBLOBs(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    List<Log> selectByExampleWithRowbounds(LogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    LogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") LogWithBLOBs record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") LogWithBLOBs record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int updateByPrimaryKeySelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Fri Dec 27 20:06:40 CST 2019
     */
    int updateByPrimaryKey(Log record);
}